name:                monadic-heap
version:             0.1.0.0
github:              "oisdk/monadic-heap"
license:             Apache-2.0
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2019 Donnacha Oisín Kidney"

description:         Please see the README on GitHub at <https://github.com/oisdk/monadic-heap#readme>

dependencies:
- base >= 4.12 && < 5
- transformers >= 0.3.0
- mtl >= 2.0.0

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
- -fwarn-redundant-constraints
- -Wcompat

library:
  source-dirs: src

tests:
  monadic-heap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monadic-heap
    - QuickCheck >= 2.12
  monadic-heap-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - monadic-heap
    - doctest
    - QuickCheck >= 2.12
